### ISSUE TITLE
Unable to register application in Azure Portal using instructions provided ("Setting up you Azure Data Explorer cluster in the Azure Portal")

### ISSUE THREAD

**Issue by hjryan** [kkneomis/kc7#60]
I'm now working through the instructions at https://github.com/kkneomis/kc7/wiki/Setting-up-you-Azure-Data-Explorer-cluster-in-the-Azure-Portal (I think this should be "your" instead of "you").

I am able to complete steps 1-3 under "Create an Azure Data Explorer Cluster" with some minor modifications in step 3:
- my subscription is a different type (student)
- I am unable to name my cluster "kc7round1" as it already exists, so named it "kc7round"

I am able to complete step 4 without issue.

Under "Register an Azure Application and give it permissions to your cluster", I am able search for "app registrations" and click on the correct icon, but the page it brings me to says that my administrator has disabled this feature:
<img width="860" alt="Screenshot 2022-11-17 at 6 58 47 PM" src="https://user-images.githubusercontent.com/5475166/202606780-0ba1ba74-34f8-4626-8865-0136f521f29a.png">

I am unable to proceed further and thus unable to configure my cluster -- I'm not sure if this is specific to my workspace (Oregon State University (OregonStateUniversity.onmicrosoft.com)) or subscription type, but it would be helpful to have a workaround for this.

**Comment by kkneomis** [comment]
@hjryan  Happy to help with this! Thanks for taking the time to look at this project. Did you just want to access the data and try out the game or did you specifically want to generate a unique data instance for your own tenant?

If you simpy want to learn from the data you can follow the instructions here to load some pre-generated data into a free kusto cluster:
https://github.com/kkneomis/kc7/wiki/No-code-Required!-Loading-the-test-KC7-cluster-into-your-free-Kusto-instance

Here's a youtube video describing the same thing
https://www.youtube.com/watch?v=aHJxEHIHq0k&feature=youtu.be&ab_channel=SimeonKakpovi

If you did want to load new data into your cluster, I am happy to help further.

**Comment by gregs1998** [comment]
Resolving this. Please reach out to us if you have any further questions!
